version: '3'
services:
  wpp-service:
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - "80:3004"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
