version: '3.9'
services:
  wpp-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3004:3004"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
