version: '3.9'
services:
  wpp-service:
    container_name: agilizone-wpp-service
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - "3004:3004"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
      - /usr/src/app/tokens
    restart: unless-stopped
